### PR TITLE
Support selected attribute for messages

### PR DESCRIPTION
**Pull request by steelbrain**
It's gonna be a callback that has the message as the first parameter so it works with arrow functions

Fixes https://github.com/steelbrain/linter/issues/1106

- [x] Implement support
- [x] Add specifications
- [x] Document change in CHANGELOG
- [x] Update wiki

### CODE REVIEW

**Comment by steelbrain** [comment]
@noseglid Doing `.call(linter, message)` got very complicated and optimizations killing so now it just calls with message, would that work for your use case?

**Comment by steelbrain** [comment]
Merging it in as this is the way it's best to do it. If you still have a use case which is not covered by this please let us know

**Comment by noseglid** [comment]
I'm sorry for my unresponsiveness. I'm away on a trip during Easter.  

Is it possible to add a custom key to the message so that I can pass arbitrary information there?

**Comment by steelbrain** [comment]
@noseglid Yeah sure, just add any of the non-standard keys and they'll be provided as is

**Pull request merged**
