### PR TITLE
fix: fix linter dock scroll

### PR DESCRIPTION
**Pull request by UziTech**
This fixes linter dock not scrolling

https://discord.com/channels/737254137690980372/737255015730774047/806537439400558602

### CODE REVIEW

**Comment by UziTech** [comment]
I don't think the linting error is realted to this PR

```
Error: ESLint configuration in .eslintrc.json » eslint-config-atomic/react is invalid:
```

**Review by aminya — APPROVED** [review]

**Comment by aminya** [comment]
Thanks!

**Comment by UziTech** [comment]
The lint issue is fixed in `eslint-config-atomic` v1.7.1

The bigger issue is that `npm` is used to install dependencies but there is no `package-lock.json` file so it installs the latest version of devdependencies instead of the version in `package.json`.

**Comment by aminya** [comment]
I updated the eslint dependency.

**Pull request merged**
