### PR TITLE
Tooltip style improvements

### PR DESCRIPTION
**Pull request by pedzed**
Using the UI variables rather than using own styles.

### CODE REVIEW

**Comment by steelbrain** [comment]
Looks too hot on my One Dark builtin theme, can you adjust the values?

**Comment by steelbrain** [comment]
Here's a before one, for the reference

**Comment by pedzed** [comment]
image

Although this works fine too, I really think that we should use the theme's UI. Just because the standard theme (or themes) don't look good should not prevent us to use the correct way.

**Comment by steelbrain** [comment]
This is the new error and warning. Looks better but needs to be a *little* bit darker :)

**Comment by pedzed** [comment]
I can make them all darker, but then again, if a theme developer decides to use a color, we change their setting. That's not what we should do.

**Comment by steelbrain** [comment]
I am personally 👍 on this
waiting on @Arcanemagus

**Comment by Arcanemagus** [comment]
On the one hand I would love to say to use the theme colors, after all that's _why_ the user has installed a custom theme. Unfortunately almost all of them seem to look _terrible_ when we do that 😕.

I'll try to check this out locally and check it out, the screenshot above seems to look fine at least.

**Comment by pedzed** [comment]
We could also give the users the option to use our custom colors, or base it on their theme.

This is how it would look like with the Material Theme ([Light UI](https://atom.io/themes/atom-material-syntax-light)):

image

**Comment by Arcanemagus** [comment]
I do like the idea of being able to force known usable colors if the user's theme is broken 😉.

**Comment by Arcanemagus** [comment]
Before:

image


After:

image

Both are usable to me, and if the "After" is using the theme colors then that's probably preferable.

**Comment by pedzed** [comment]
> Both are usable to me, and if the "After" is using the theme colors then that's probably preferable.

No, it's not (completely) as 257e39b49 reverted it.

**Comment by steelbrain** [comment]
F it, it's been open for too long and is pretty good 😛

**Pull request merged**
