### PR TITLE
Fixed icons misaligned with and below the baseline

### PR DESCRIPTION
**Pull request by ipaintcode**
Fixed icons that are vertically misaligned:

Issue:
icons

Resolved:

resolved

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Thanks for looking into this @ipaintcode! I'm marking this as a duplicate of #439 since that simplifies the generated DOM as well with the same result.

**Comment by steelbrain** [comment]
Thank you so much for this @ipaintcode

Really appreciate you contributing this fix 🙇  We went with a slightly different route in #439

**Comment by Arcanemagus** [comment]
Duplicate of #439

**Comment by ipaintcode** [comment]
No worries, glad it got fixed!

**Pull request closed without merging**
