### PR TITLE
Set max-width for linter tooltip for readability.

### PR DESCRIPTION
**Pull request by szhu**
Line length based off this article, which suggests 21em-30em for readability. Added a few ems just in case.
http://maxdesign.com.au/articles/ideal-line-length-in-ems/

### CODE REVIEW

**Comment by szhu** [comment]
Actually, 35em is probably still too short. Sometimes linter messages contain code excerpts, which can look funky if they're narrowly wrapped.

I've changed the width to `64em`, which is a little more than 100chars on Mac.

**Comment by steelbrain** [comment]
Hi @szhu 

Thanks for working on this, could you please attach a screenshot of the new behavior? Thanks!

**Comment by szhu** [comment]
**Before:**
image

**After:**
image

Ideally, max-width should be a setting, but I don't have time to figure that out. I think 64em is a conservative and reasonable default.

**Comment by steelbrain** [comment]
Thank you for working on this!

**Comment by Arcanemagus** [comment]
Note that this potentially breaks the output for content that _depends_ on the text not being wrapped, such as Flow type definitions (https://github.com/facebook-atom/atom-ide-ui/pull/164#issuecomment-364262481)

**Comment by szhu** [comment]
@Arcanemagus does the text in that example exceed 100chars? I think most command-line tools expect no more than 100chars width.

**Comment by Arcanemagus** [comment]
You'd expect most CLI tools to _work_ and `flow` breaks that assumption often enough that I wouldn't trust it to be keeping under 100 characters 😆.

I'm not sure in that particular example as it's not mine, I haven't tested this PR's changes yet myself on `perlcritic`'s output which _might_ hit the same thing.

**Comment by szhu** [comment]
My rationale is that CLI tools can't expect the terminal width to be over 100 chars… but yeah I'm sure there are exceptions

**Pull request merged**
